const data = [
  {
    id: 1,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
  {
    id: 2,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
  {
    id: 3,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
  {
    id: 4,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
  {
    id: 5,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
  {
    id: 6,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
  {
    id: 7,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
  {
    id: 8,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
  {
    id: 9,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
  {
    id: 10,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
  {
    id: 11,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
  {
    id: 12,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
  {
    id: 13,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
  {
    id: 14,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
  {
    id: 15,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
  {
    id: 16,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
  {
    id: 17,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
  {
    id: 18,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
  {
    id: 19,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
  {
    id: 20,
    logo: "/assets/images/logocard.png",
    wave: "/assets/images/wave.png",
    chip: "/assets/images/chip.png",
    digits: "XXXX XXXX XXXX XXXX",
    name: "MADUKA CHINWE",
    year: "XX/XX",
    isChecked: false,
  },
];

export default data;
